name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup MoonBit
        uses: moonbitlang/setup-moonbit@v1

      - name: Moon format check
        run: moon fmt --check

      - name: Moon type check
        run: moon check --deny-warn

      - name: Moon tests
        run: moon test --deny-warn

      - name: Moon benchmarks
        run: moon bench

      - name: CLI smoke test
        run: moon run src/cli -- --help
